version: "3"
services:

  pyspark:
    volumes:
      - $PATH_LOCAL_USER:/home/jovyan/work
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    networks:
      - pyspark-net
    deploy:
      restart_policy:
        condition: on-failure

  postgres:
    image: postgres:10
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/home/data
      - ./data/creacion_tablas.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "data"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - pyspark-net
    deploy:
      restart_policy:
        condition: on-failure

networks:
  pyspark-net: